[logging]
level = "info"

[run]
environment = "docker"
port = 1000

[build]
environment = "docker"
entrypoint = "make"

[git]
environment = "docker"

[git.vpn]
enabled = true
host = "vpn.example.org"
port = 443
